export const SECTIONS = [
  { id: "à propos", label: "À propos" },
  { id: "compétences", label: "Compétences" },
  { id: "certifications", label: "Certifications" },
  { id: "expériences", label: "Expériences" },
  { id: "projets", label: "Projets" },
  { id: "jeux vidéo", label: "Jeux vidéo" },
  { id: "formations", label: "Formations" },
  { id: "recommandations", label: "Recommandations" },
  { id: "contact", label: "Contact" },
]

export const PROFILE_IMAGE =
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pp-w2GG1DuljKwkZI0wCuoAPwbprQNHF2.png"

export const portfolioData = {
  experiences: [
    {
      title: "Alternant Développeur Full Stack",
      company: "ICMAAE - Institut de la Connaissance des Méthodes d'Apprentissage Autonome et d'Eveil",
      period: "Août 2024 - Présent",
      location: "Évian-les-Bains, Auvergne-Rhône-Alpes, France · À distance",
      description: [
        "Optimiser l'ergonomie et la navigation des logiciels propriétaires",
        "Développer et intégrer des maquettes avec divers langages de programmation",
        "Contribuer aux corrections techniques et assurer le respect des normes",
        "Concevoir des éléments techniques pour sites et logiciels propriétaires",
        "Travailler sur les bases de données",
        "Approfondir les connaissances en PHP, Ruby, Python, Java, .Net et bases de données SQL Serveur, MySQL",
        "Se familiariser avec les API",
        "Développer des solutions et applications web",
        "Concevoir et développer la plateforme de gestion des contenus",
      ],
      technologies: [
        "Next.js",
        "Tailwind CSS",
        "Docker",
        "Django",
        "Python",
        "SQL Server",
        "MySQL",
        "PHP",
        "Java",
        ".NET",
        "API de services web",
        "Django REST",
        "Ruby",
        "PostgreSQL",
        "Methode scrum",
        "Figma",
      ],
      logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Capture%20d%E2%80%99%C3%A9cran%202025-03-07%20173026-JMEFAYd4hdyV0FZtwN8gW0tZl57Ufh.png",
      fileType: "js",
    },
    {
      title: "Stage Développeur Front-End ReactJS",
      company: "Snowpack",
      period: "Décembre 2023 - Janvier 2024",
      location: "Palaiseau, Île-de-France, France · Sur site",
      description: [
        "Initiation au Framework REACT.js",
        "Amélioration de l'application de démonstration de l'outil Snowpack",
        "Amélioration du site Web Snowpack, participer à l'administration du site web",
      ],
      technologies: [
        "Linux",
        "React.js",
        "Ubuntu",
        "WordPress",
        "API de services web",
        "JavaScript",
        "Figma",
        "Node.js",
        "jQuery",
        "GitLab",
        "AJAX",
        "Git",
      ],
      logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images.jpg-qSTIMiYVXgrT0ODA7doNMDjm8yBdaj.jpeg",
      fileType: "jsx",
    },
    {
      title: "Stage Développeur Front-End Angular",
      company: "Mutuaide",
      period: "Mai 2023 - Juillet 2023",
      location: "Noisy-le-Grand, Île-de-France, France · Sur site",
      description: [
        "Migrer une interface Angular 7 vers Angular 16",
        "Principes et organisation d'une application Angular",
        "Consommer un Webservice avec Angular",
        "UI Ng Prime",
        "Débogage",
      ],
      technologies: ["Angular", "TypeScript", "Node.js", "API de services web", "Débogage"],
      logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo2-q0sUolpa2xUSB1Enb2rC8NjPDurp6t.png",
      fileType: "ts",
    },
    {
      title: "Stagiaire Développeur WordPress",
      company: "Les Apprentis Dev",
      period: "Juillet 2022",
      location: "Île-de-France, France · À distance",
      description: ["Développement d'une plateforme web", "Adaptation des exigences du cahier des charges"],
      technologies: ["Adaptation des exigences d'un cahier des charges", "WordPress", "Développement de plateforme"],
      logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images-eQyypqydJKHAQesYfTn4tuyg6HkQWh.png",
      fileType: "php",
      fileName: "LesApprentisDev.php",
    },
  ],
}
